<div id="infyLoader" class="infy-loader">
    {{--<svg class="loader-position" width="150px" height="75px" viewBox="0 0 187.3 93.7"
         preserveAspectRatio="xMidYMid meet">
        <path stroke="#00c6ff" id="outline" fill="none" stroke-width="5" stroke-linecap="round" stroke-linejoin="round"
              stroke-miterlimit="10"
              d="M93.9,46.4c9.3,9.5,13.8,17.9,23.5,17.9s17.5-7.8,17.5-17.5s-7.8-17.6-17.5-17.5c-9.7,0.1-13.3,7.2-22.1,17.1 				c-8.9,8.8-15.7,17.9-25.4,17.9s-17.5-7.8-17.5-17.5s7.8-17.5,17.5-17.5S86.2,38.6,93.9,46.4z"/>
        <path id="outline-bg" opacity="0.05" fill="none" stroke="#f5981c" stroke-width="5" stroke-linecap="round"
              stroke-linejoin="round" stroke-miterlimit="10"
              d="				M93.9,46.4c9.3,9.5,13.8,17.9,23.5,17.9s17.5-7.8,17.5-17.5s-7.8-17.6-17.5-17.5c-9.7,0.1-13.3,7.2-22.1,17.1 				c-8.9,8.8-15.7,17.9-25.4,17.9s-17.5-7.8-17.5-17.5s7.8-17.5,17.5-17.5S86.2,38.6,93.9,46.4z"/>
    </svg>--}}
    <div class="loadingio-spinner-spinner-ilbhh257ibl center-screen"><div class="ldio-ro5qwccubo">
            <div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div>
        </div></div>
    <style type="text/css">
        @keyframes ldio-ro5qwccubo {
            0% { opacity: 1 }
            100% { opacity: 0 }
        }
        .ldio-ro5qwccubo div {
            left: 64.39px;
            top: 32.88px;
            position: absolute;
            animation: ldio-ro5qwccubo linear 1s infinite;
            background: #fe9004;
            width: 8.22px;
            height: 16.44px;
            border-radius: 4.11px / 8.22px;
            transform-origin: 4.11px 35.620000000000005px;
        }.ldio-ro5qwccubo div:nth-child(1) {
             transform: rotate(0deg);
             animation-delay: -0.9166666666666666s;
             background: #fe9004;
         }.ldio-ro5qwccubo div:nth-child(2) {
              transform: rotate(30deg);
              animation-delay: -0.8333333333333334s;
              background: #fe9004;
          }.ldio-ro5qwccubo div:nth-child(3) {
               transform: rotate(60deg);
               animation-delay: -0.75s;
               background: #fe9004;
           }.ldio-ro5qwccubo div:nth-child(4) {
                transform: rotate(90deg);
                animation-delay: -0.6666666666666666s;
                background: #fe9004;
            }.ldio-ro5qwccubo div:nth-child(5) {
                 transform: rotate(120deg);
                 animation-delay: -0.5833333333333334s;
                 background: #fe9004;
             }.ldio-ro5qwccubo div:nth-child(6) {
                  transform: rotate(150deg);
                  animation-delay: -0.5s;
                  background: #fe9004;
              }.ldio-ro5qwccubo div:nth-child(7) {
                   transform: rotate(180deg);
                   animation-delay: -0.4166666666666667s;
                   background: #fe9004;
               }.ldio-ro5qwccubo div:nth-child(8) {
                    transform: rotate(210deg);
                    animation-delay: -0.3333333333333333s;
                    background: #fe9004;
                }.ldio-ro5qwccubo div:nth-child(9) {
                     transform: rotate(240deg);
                     animation-delay: -0.25s;
                     background: #fe9004;
                 }.ldio-ro5qwccubo div:nth-child(10) {
                      transform: rotate(270deg);
                      animation-delay: -0.16666666666666666s;
                      background: #fe9004;
                  }.ldio-ro5qwccubo div:nth-child(11) {
                       transform: rotate(300deg);
                       animation-delay: -0.08333333333333333s;
                       background: #fe9004;
                   }.ldio-ro5qwccubo div:nth-child(12) {
                        transform: rotate(330deg);
                        animation-delay: 0s;
                        background: #fe9004;
                    }
        .loadingio-spinner-spinner-ilbhh257ibl {
            width: 137px;
            height: 137px;
            display: inline-block;
            overflow: hidden;
            background: none;
        }
        .ldio-ro5qwccubo {
            width: 100%;
            height: 100%;
            position: relative;
            transform: translateZ(0) scale(1);
            backface-visibility: hidden;
            transform-origin: 0 0; /* see note above */
        }
        .ldio-ro5qwccubo div { box-sizing: content-box; }
        .center-screen {
            position: absolute;
            top: 50%;
            left: 50%;
            margin-right: -50%;
            transform: translate(-50%, -50%);
        }
        /* generated by https://loading.io/ */
    </style>

</div>
